In [7]:
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_digits

In [8]:
df = pd.DataFrame(load_digits().data)

In [9]:
df['target'] = load_digits().target
df

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0,9
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0,0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0,8
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0,9
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0,8

In [10]:
#df1 = df[['sepal width (cm)','sepal length (cm)','petal length (cm)','petal width (cm)']][df['target']==1]
df.columns

Index([       0,        1,        2,        3,        4,        5,        6,
              7,        8,        9,       10,       11,       12,       13,
             14,       15,       16,       17,       18,       19,       20,
             21,       22,       23,       24,       25,       26,       27,
             28,       29,       30,       31,       32,       33,       34,
             35,       36,       37,       38,       39,       40,       41,
             42,       43,       44,       45,       46,       47,       48,
             49,       50,       51,       52,       53,       54,       55,
             56,       57,       58,       59,       60,       61,       62,
             63, 'target'],
      dtype='object')

In [11]:
count =0
for name in range(len(df.columns)):
    globals()['col' + str(count)] = df.columns[name]
    count +=1
col1 # displays the name of the second column

1

In [12]:
i = 0
for n in range(5):
    globals()["df" + str(i)] = df[df.columns.to_list()][df['target']==i]
    i += 1

df0
#look at the target it just displays the info connected to just number 0

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
10,0.0,0.0,1.0,9.0,15.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,10.0,13.0,3.0,0.0,0.0,0
20,0.0,0.0,3.0,13.0,11.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,12.0,13.0,4.0,0.0,0.0,0
30,0.0,0.0,10.0,14.0,11.0,3.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,11.0,16.0,12.0,3.0,0.0,0.0,0
36,0.0,0.0,6.0,14.0,10.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,7.0,16.0,11.0,1.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1739,0.0,0.0,10.0,11.0,7.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,7.0,12.0,8.0,0.0,0.0,0.0,0
1745,0.0,0.0,7.0,14.0,8.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,7.0,0.0,0.0,0.0,0
1746,0.0,0.0,9.0,15.0,6.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,8.0,15.0,11.0,4.0,0.0,0.0,0
1768,0.0,0.0,5.0,16.0,10.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,15.0,16.0,8.0,1.0,0.0,0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0,0

In [24]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
mod = SVC(kernel = 'rbf')
mod

SVC()

In [63]:

inpu = df.drop('target',axis='columns')
out = df.target
inpu_train , inpu_test , out_train ,out_test = train_test_split(inpu,out,test_size=0.2,random_state=12)

In [64]:
mod.fit(inpu_train,out_train)

SVC()

In [65]:
mod.score(inpu_train,out_train)

0.9951287404314544

In [66]:
mod.score(inpu_test,out_test)

0.9916666666666667

In [67]:
mod2 = SVC(kernel='linear')
mod2.fit(inpu_train,out_train)
mod2.score(inpu_test,out_test)

0.975

In [69]:
import pickle
with open('model_pickle','wb') as file: # write binary 
    pickle.dump(mod,file) # put model into file